version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shigoto

networks:
  shigoto:
    external:
      name: shigoto_network
