name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Declare variables
        id: var
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the stack
        run: docker build -t shigoto_production_result_service .

      - name: Tag Docker images
        run: |
          docker tag shigoto_production ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_production_result_service:${{ steps.vars.outputs.sha_short }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_production_result_service:${{ steps.vars.outputs.sha_short }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Shigoto-Q/sgt-infrastructure
          event-type: go-result-service-build-successful
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ steps.vars.outputs.sha_short }}"}'